# Travis Configuration File

language: php
php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - '7.1'
  - nightly
  
before-script:
  - composer install

matrix:
  include:
    - php: nightly
      env:
      - OPCODE_CACHE=apc
    - php: 7.1
      env:
      - OPCODE_CACHE=apc
    - php: 7.0
      env:
      - OPCODE_CACHE=apc
      - DISABLE_XDEBUG=true
      - LINT=true
    - php: 5.6
      env:
      - OPCODE_CACHE=apc
      - DISABLE_XDEBUG=true
    - php: 5.5
      env:
      - OPCODE_CACHE=apc
      - DISABLE_XDEBUG=true
    - php: 5.4
      env:
      - OPCODE_CACHE=apc
      - DISABLE_XDEBUG=true
    - php: 5.3
      env:
      - OPCODE_CACHE=apc
      - DISABLE_XDEBUG=true
