# Travis Configuration File

language: php

php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - nightly

sudo: false

before_script:
  - composer install 
  - curl -X PUT http://localhost:5984/testdb

script: vendor/bin/phpunit --coverage-clover=coverage.xml

services:
  - couchdb

after_success:
  - bash <(curl -s https://codecov.io/bash)