#!/usr/bin/env php
<?php

foreach (
    [
        __DIR__ . '/../autoload.php',
        __DIR__ . '/../../autoload.php',
        __DIR__ . '/../vendor/autoload.php',
        __DIR__ . '/vendor/autoload.php',
        __DIR__ . '/../../vendor/autoload.php'
    ] as $file
) {
    if (file_exists($file)) {
        define('AUTOLOAD_PHP_FILE', $file);
        break;
    }    
}

if (!defined('AUTOLOAD_PHP_FILE')) {
     fwrite(STDERR,
        'You need to set up the project dependencies using the following commands:' . PHP_EOL .
        'wget http://getcomposer.org/composer.phar' . PHP_EOL .
        'php composer.phar install' . PHP_EOL
    );
    die(1);
}

require AUTOLOAD_PHP_FILE;

use Chemem\Fauxton\Console;
use Chemem\Fauxton\Config\State;
use \Chemem\Bingo\Functional\Algorithms as A;
use \Chemem\Bingo\Functional\Functors\Monads as M;
use \Chemem\Bingo\Functional\Functors\Monads\IO;

function errorHandler(string $msg, bool $type = false) : bool
{
    $err = M\bind(function ($msg) use ($type) {
        $handler = A\compose(
            A\partial(A\concat, ' ', $type ? 'Exception' : 'Error:'),
            A\partialRight(Console\color, $type ? 'red' : 'yellow'), 
            A\partial('printf', '%s'), 
            function ($content) : bool {
                return $content > 0 ? true : false;
            },
            IO\IO
        );
        return $handler($msg);
    }, IO\IO($msg));

    return $err->exec();
}

set_exception_handler(function ($exception) {
    return errorHandler($exception->getMessage(), true);
});

set_error_handler(function ($errno, $errstr) {
    return errorHandler($errstr);
});

function main() : IO
{
    $result = A\compose(
        A\constantFunction(Console\replPrompt()),
        A\constantFunction(M\mcompose(function ($fgets) {
            $repl = A\compose($fgets, Console\execCmd, IO\IO);
            return $repl(\STDIN);
        }, IO\putStr)(IO\IO(null)))
    );

    return $result(null)->exec();
}

M\bind(function (string $msg) {
    $result = A\compose(A\partial('printf', '%s'), IO\IO);
    return $result($msg);
}, IO\IO(A\concat(\PHP_EOL, 'Fauxton Console', 'Built By Lochemem Bruno Michael', '')));

while (true) IO\_print(main());